name: CampExplorer CI/CD

on:
  push:
    branches:
      - main

jobs:
  cicd-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Run Linter
        run: npm run linter

      - name: Deploy Service
        run: curl "https://api.render.com/deploy/srv-ciufnq5iuiedpv0091t0?key=XmfMzcU18IA"
